create table users
(
    id          UUID PRIMARY KEY,
    email       varchar(100) unique not null,
    password    varchar(100) not null,
    first_name  varchar(20)  not null,
    second_name varchar(20)  not null,
    role        varchar      not null
);


create table refresh_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiry_date TIMESTAMPTZ  NOT NULL,
    token       varchar(255) not null,
    user_id     UUID         not null,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

create table brands
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(20) not null unique

);

create table categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(20) not null unique
);

create table sub_categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(20) not null unique ,
    category_id BIGINT      not null,
    FOREIGN KEY (category_id) REFERENCES categories (id)
);

create table products
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(20) not null unique,
    brand_id        BIGINT      not null,
    sub_category_id BIGINT      not null,
    description     varchar(60) not null,
    FOREIGN KEY (brand_id) REFERENCES brands (id),
    FOREIGN KEY (sub_category_id) REFERENCES sub_categories (id)
);

create table product_variants
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price DOUBLE PRECISION not null,
    product_id BIGINT not null,
    FOREIGN KEY (product_id) REFERENCES products (id)
);

create table inventory
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    available_quantity Int    not null,
    product_variant_id BIGINT not null,
    FOREIGN KEY (product_variant_id) REFERENCES product_variants (id)
);

create table carts
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID not null unique ,
    FOREIGN KEY (user_id) REFERENCES users (id)
);
create table cart_items
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity           Int    not null,
    cart_id            BIGINT not null,
    product_variant_id BIGINT not null,
    FOREIGN KEY (cart_id) REFERENCES carts (id),
    FOREIGN KEY (product_variant_id) REFERENCES product_variants (id)
);
create table attributes
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(20) not null unique
);

create table attribute_values
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value        varchar(20) not null unique,
    attribute_id BIGINT      not null,
    FOREIGN KEY (attribute_id) REFERENCES attributes (id)
);

create table variant_attribute_values
(
    product_variant_id BIGINT,
    attribute_value_id BIGINT,
    primary key (product_variant_id, attribute_value_id),
    FOREIGN KEY (product_variant_id) REFERENCES product_variants (id),
    FOREIGN KEY (attribute_value_id) REFERENCES attribute_values (id)
);

create table orders
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    TIMESTAMP NOT NULL,
    discount_rate int         not null,
    status        varchar(15) not null,
    total_price DOUBLE PRECISION not null,
    user_id       UUID        not null,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

create table order_items
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity           int    not null,
    product_variant_id BIGINT not null,
    order_id           BIGINT not null,
    FOREIGN KEY (product_variant_id) REFERENCES product_variants (id),
    FOREIGN KEY (order_id) REFERENCES orders (id)
);